CREATE SEQUENCE CUSTSEQ
	START WITH 500000001
	INCREMENT BY 1
	MAXVALUE 600000000
	CYCLE;


CREATE TABLE CUSTOMERDETAILS(
	USERNAME VARCHAR(255),
	SSN NUMBER(12) PRIMARY KEY,
	EMAIL VARCHAR(255),
	ADDRESS VARCHAR(255),
	PASSWORD VARCHAR(255)
)

ALTER TABLE CUSTOMERDETAILS ADD PRIMARY KEY (SSN) 

CREATE TABLE SAVINGSACCOUNTDETAILS(
	ACCOUNTID NUMBER(12),
	ACCOUNTTYPE VARCHAR(255),
	BALANCE NUMBER(10,2),
	STATUS VARCHAR(255),
	SSN REFERENCES CUSTOMERDETAILS(SSN)	ON DELETE CASCADE 
)



ALTER TABLE ACCOUNTDETAILS RENAME TO SAVINGSACCOUNTDETAILS

DROP TABLE CURRENTACCOUNTDETAILS;

CREATE TABLE CURRENTACCOUNTDETAILS(
	ACCOUNTID NUMBER(12),
	ACCOUNTTYPE VARCHAR(255),
	BALANCE NUMBER(10,2),
	STATUS VARCHAR(255),
	SSN REFERENCES CUSTOMERDETAILS(SSN)	ON DELETE CASCADE 
)


TRUNCATE TABLE CURRENTACCOUNTDETAILS; 
ALTER TABLE CURRENTACCOUNTDETAILS ADD PRIMARY KEY (ACCOUNTID) 
ALTER TABLE SAVINGSACCOUNTDETAILS ADD PRIMARY KEY (ACCOUNTID) 
INSERT INTO SAVINGSACCOUNTDETAILS VALUES(1674531,'Savings',5000, 'Active',500000001)
INSERT INTO SAVINGSACCOUNTDETAILS VALUES(1674532,'Savings',10000, 'Active',500000002)

INSERT INTO CURRENTACCOUNTDETAILS VALUES(1774531,'Current',5000, 'Active',500000001)
INSERT INTO CURRENTACCOUNTDETAILS VALUES(1774532,'Current',10000, 'Active',500000002)

DELETE FROM CURRENTACCOUNTDETAILS WHERE ACCOUNTID = 1774532;

SELECT * FROM SAVINGSACCOUNTDETAILS

SELECT * FROM CUSTOMERDETAILS
SELECT * FROM SAVINGSACCOUNTDETAILS
select ACCOUNTID from CURRENTACCOUNTDETAILS

DROP TABLE CUSTOMERDETAILS;
DROP TABLE CURRENTACCOUNTDETAILS;
DROP TABLE SAVINGSACCOUNTDETAILS;

SELECT * FROM CUSTOMERDETAILS WHERE USERNAME = 'Barani'